version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: java-backend
    ports:
      - "8080:8080"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
